export const INCREMENT_PRODUCT_ORDER = "INCREMENT_PRODUCT_ORDER";
export const DECREMENT_PRODUCT_ORDER = "DECREMENT_PRODUCT_ORDER";
export const DELETE_PRODUCT_ORDER = "DELETE_PRODUCT_ORDER";
export const PUSH_PRODUCTS_BY_CATEGORY = "PUSH_PRODUCTS_BY_CATEGORY";
export const CLEAR_ORDERS = "CLEAR_ORDERS";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const ADD_USER = "ADD_USER";
export const FETCH_USERS = "FETCH_USERS";

export const ADD_STORE = "ADD_STORE";
export const FETCH_STORES = "FETCH_STORES";

export const ADD_CHECKOUT = "ADD_CHECKOUT";

export const SIGN_UP_ADMIN = "SIGN_UP_ADMIN";
export const SIGN_IN_ADMIN = "SIGN_IN_ADMIN";
