export const INCREMENT_PRODUCT_ORDER = "INCREMENT_PRODUCT_ORDER";
export const DECREMENT_PRODUCT_ORDER = "DECREMENT_PRODUCT_ORDER";
export const DELETE_PRODUCT_ORDER = "DELETE_PRODUCT_ORDER";
export const PUSH_PRODUCTS_BY_CATEGORY = "PUSH_PRODUCTS_BY_CATEGORY";
